---
apiVersion: '2'
projectId: f56d44bb-8261-41e0-b3ee-af37931cb493
version: 33
created: '2021-06-08T18:37:52.440Z'
updated: '2021-06-11T13:59:47.044Z'
defaultLocale: en-us
locales:
- en-us
schemaVersion: 3.2.0
queries:
  getMyProfile:
    shape: Profile
    resolver:
      name: takeshape:find
      service: takeshape:local
      options:
        model: Profile
      argsMapping:
        where.id.eq:
        - - get
          - path: claims.sub
    description: Get my Profile
  getProfile:
    shape: Profile
    resolver:
      name: takeshape:get
      service: takeshape:local
      options:
        model: Profile
    description: Get a Profile by ID
    args: TSGetArgs<Profile>
  getProfileList:
    shape: PaginatedList<Profile>
    resolver:
      name: takeshape:list
      service: takeshape:local
      options:
        model: Profile
    description: Returns a list Profile in natural order.
    args: TSListArgs<Profile>
mutations:
  upsertMyProfile:
    shape: Profile
    resolver:
      resultsMapping:
      - - get
        - path: steps.createProfile.result
      - - get
        - path: steps.updateProfile.result
      compose:
      - if: "!isEmpty(claims.sub)"
        id: existingProfile
        argsMapping:
          where.id.eq:
          - - get
            - path: claims.sub
        name: takeshape:find
        service: takeshape:local
        options:
          model: Profile
      - if: isEmpty(steps.existingProfile)
        id: createProfile
        argsMapping:
          input.id:
          - - get
            - path: claims.sub
          input.email:
          - - get
            - path: claims.email
          input.firstName:
          - - get
            - path: args.firstName
          input.lastName:
          - - get
            - path: args.lastName
          input.bio:
          - - get
            - path: args.bio
        name: takeshape:create
        service: takeshape:local
        options:
          model: Profile
      - if: "!isEmpty(steps.existingProfile)"
        id: updateProfile
        argsMapping:
          input._id:
          - - get
            - path: steps.existingProfile._id
          input.email:
          - - get
            - path: claims.email
          input.firstName:
          - - get
            - path: args.firstName
          input.lastName:
          - - get
            - path: args.lastName
          input.bio:
          - - get
            - path: args.bio
          input.avatar.id:
          - - get
            - path: args.avatarId
        name: takeshape:update
        service: takeshape:local
        options:
          model: Profile
    description: Upsert My Profile
    args: UpsertMyProfileInput
  updateProfile:
    shape: UpdateResult<Profile>
    resolver:
      name: takeshape:update
      service: takeshape:local
      options:
        model: Profile
    description: Update Profile
    args: UpdateArgs<Profile>
  createProfile:
    shape: CreateResult<Profile>
    resolver:
      name: takeshape:create
      service: takeshape:local
      options:
        model: Profile
    description: Create Profile
    args: CreateArgs<Profile>
  duplicateProfile:
    shape: DuplicateResult<Profile>
    resolver:
      name: takeshape:duplicate
      service: takeshape:local
      options:
        model: Profile
    description: Duplicate Profile
    args: DuplicateArgs<Profile>
  deleteProfile:
    shape: DeleteResult<Profile>
    resolver:
      name: takeshape:delete
      service: takeshape:local
      options:
        model: Profile
    description: Delete Profile
    args: DeleteArgs<Profile>
shapes:
  UpsertMyProfileInput:
    id: UpsertMyProfileInput
    name: UpsertMyProfileInput
    title: UpsertMyProfileInput
    schema:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        bio:
          type: string
        avatarId:
          type: string
  Profile:
    id: 5NtDf9shq
    name: Profile
    title: Profile
    workflow: default
    model:
      type: multiple
    schema:
      type: object
      properties:
        id:
          minLength: 1
          type: string
          description: ''
          title: ID
          "@mapping": takeshape:local:Profile.BMKpXA3Z9
        firstName:
          minLength: 0
          type: string
          description: ''
          title: First Name
          "@mapping": takeshape:local:Profile.s4H8TVVHd
        lastName:
          minLength: 0
          type: string
          description: ''
          title: Last Name
          "@mapping": takeshape:local:Profile.P2YHMZMX6
        email:
          minLength: 0
          type: string
          description: ''
          title: Email
          "@mapping": takeshape:local:Profile.YxXDEC3VM
        bio:
          minLength: 0
          type: string
          description: ''
          title: Bio
          "@mapping": takeshape:local:Profile._OzVMMJ0Y
        avatar:
          description: ''
          "$ref": "#/shapes/TSRelationship/schema"
          "@relationship":
            shapeIds:
            - ASSET
          title: Avatar
          "@mapping": takeshape:local:Profile.k0Ha4O7oV
      required:
      - id
workflows: {}
forms:
  Profile:
    default:
      properties:
        id:
          widget: singleLineText
        firstName:
          widget: singleLineText
        lastName:
          widget: singleLineText
        email:
          widget: singleLineText
        bio:
          widget: paragraphText
        avatar:
          widget: image
      order:
      - id
      - firstName
      - lastName
      - email
      - bio
      - avatar
services:
  my-auth-0:
    id: my-auth-0
    provider: auth0
    title: My Auth0
    serviceType: authentication
    authenticationType: none
    options:
      domain: dev-by9w1mxg.us.auth0.com
      audience: https://api.takeshape.io/project/f56d44bb-8261-41e0-b3ee-af37931cb493/my-auth-0
dataKey: AQIDAHi9nATJb1LYgj5u7ShOGp43y2H6TuckRKGDlwTU4b6ryQHskEThHoHhklwoe2Rw4/jmAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM3DJr8ECSFYbCouO6AgEQgDtSErD6WdvvifPkue9Yb8cMrQ6DVPNK/2lFWwzyNOkHYq6tcg1kTIq/pWEzSL3CmSqDMS19/pZaQYy3dA==

